### ISSUE TITLE
Fix rotation from viewangle, mouse interaction.

### ISSUE THREAD

**Issue by siggsa** [andesyv/megatron3000#23] opened 2021-03-23 09:34 UTC

**Comment by andesyv** [comment] 2021-03-23 13:47
It looks like the issue is caused by the rotation being applied in the local space of the model. Might need to convert the transformation from view space to local space before applying.

**Comment by andesyv** [comment] 2021-03-29 15:50
Fixed in #28

**Closed as completed** 2021-03-29 15:50 UTC
Labels: bug
